language: php
php:
  - 5.5
  - 5.4
  - 5.3
  - hhvm
env:
  global:
    - PLUGIN_NAME=WirecardCheckoutSeamless
    - REQUIRE=""
    - COVERALLS=1
  matrix:
    - CAKE_VERSION=2.4
    - CAKE_VERSION=2.5
    - CAKE_VERSION=2.6
before_script:
  - git clone https://github.com/hakito/travis.git --depth 1 ../travis
  - ../travis/before_script.sh
script:
  - ../travis/script.sh
after_success:
  - ../travis/after_success.sh
